2013/08/07 07:23:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2
HTTP_REFERER=http://localhost/index.php?r=gii/controller
---
2013/08/07 07:23:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "token".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('token')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('token')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2/token
---
2013/08/07 07:23:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "token".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('token')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('token')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2/token
---
2013/08/07 07:24:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "token".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('token')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('token')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2/token
---
2013/08/07 07:24:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "token".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('token')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('token')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2/token
---
2013/08/07 07:24:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "token".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('token')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('token')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2/token
---
2013/08/07 07:24:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "token".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('token')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('token')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2/token
---
2013/08/07 07:24:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "token".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('token')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('token')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2/token
---
2013/08/07 07:24:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "token".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('token')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('token')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2/token
---
2013/08/07 07:24:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "token".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('token')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('token')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2/token
---
2013/08/07 07:24:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "token".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('token')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('token')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=oauth2/token
---
2013/08/07 07:24:11 [error] [php] include(OAuth.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\oauthserver\protected\controllers\Oauth2Controller.php(7): spl_autoload_call()
#1 D:\srv\www\framework\web\actions\CInlineAction.php(49): Oauth2Controller->actionToken()
#2 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 D:\srv\www\framework\web\CController.php(286): Oauth2Controller->runAction()
#4 D:\srv\www\framework\web\CController.php(265): Oauth2Controller->runActionWithFilters()
#5 D:\srv\www\framework\web\CWebApplication.php(282): Oauth2Controller->run()
#6 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 D:\srv\www\oauthserver\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=oauth2/token
in D:\srv\www\oauthserver\protected\controllers\Oauth2Controller.php (7)
in D:\srv\www\oauthserver\index.php (13)
2013/08/07 07:31:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:33:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:33:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:33:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:33:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:33:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:33:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/oauth2/
---
2013/08/07 07:34:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:34:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/oauth2
---
2013/08/07 07:35:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:35:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:35:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:35:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:35:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:35:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:35:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:35:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:35:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:37:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:37:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:37:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:37:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:37:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:37:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:37:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\oauthserver\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:44:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:44:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:44:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:49:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:49:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:49:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:49:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:52:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:54:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:54:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:54:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:54:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:54:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:54:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:54:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:54:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:54:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:55:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:55:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:55:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:55:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:55:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:55:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:58:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:58:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:58:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 07:58:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:00:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "authorize.php".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('authorize.php')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('authorize.php')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/oauth2/authorize.php?response_type=code&client_id=testclient&state=xyz
---
2013/08/07 08:00:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:00:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:00:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:01:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:01:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:01:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:02:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:02:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:02:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:02:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:02:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:02:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:02:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:02:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:04:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:04:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:05:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:05:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:05:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:05:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:06:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:07:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:07:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:07:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:09:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:09:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:09:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:09:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:09:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:09:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 08:31:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2013/08/07 09:15:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2
---
2013/08/07 09:15:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "authrozix".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('authrozix')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('authrozix')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authrozi...')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authrozix
---
2013/08/07 19:05:05 [error] [exception.PDOException] exception 'PDOException' with message 'SQLSTATE[HY000] [1049] Unknown database 'oauth2'' in D:\srv\www\OAuth2-for-Yii\protected\extensions\oauth2\OAuth2\Storage\Pdo.php:41
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\extensions\oauth2\OAuth2\Storage\Pdo.php(41): PDO->__construct('mysql:dbname=oa...', 'root', '')
#1 D:\srv\www\OAuth2-for-Yii\protected\extensions\oauth2\OAuth.php(23): OAuth2\Storage\Pdo->__construct(Array)
#2 D:\srv\www\OAuth2-for-Yii\protected\controllers\Oauth2Controller.php(8): OAuth->__construct(Array)
#3 D:\srv\www\framework\web\CWebApplication.php(281): Oauth2Controller->init()
#4 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#5 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#6 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/07 19:05:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/07 21:34:25 [error] [exception.InvalidArgumentException] exception 'InvalidArgumentException' with message 'Argument "is_authorized" must be a boolean.  This method must know if the user has granted access to the client.' in D:\srv\www\OAuth2-for-Yii\protected\extensions\oauth2\OAuth2\Controller\AuthorizeController.php:64
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\extensions\oauth2\OAuth2\Server.php(232): OAuth2\Controller\AuthorizeController->handleAuthorizeRequest(Object(OAuth2\Request), Object(OAuth2\Response), NULL, NULL)
#1 D:\srv\www\OAuth2-for-Yii\protected\extensions\oauth2\OAuth.php(72): OAuth2\Server->handleAuthorizeRequest(Object(OAuth2\Request), Object(OAuth2\Response), NULL)
#2 D:\srv\www\OAuth2-for-Yii\protected\controllers\Oauth2Controller.php(17): OAuth->authorize()
#3 D:\srv\www\framework\web\actions\CInlineAction.php(49): Oauth2Controller->actionAuthorize()
#4 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('authorize')
#8 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#9 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize?response_type=code&client_id=testclient&state=xyz
---
2013/08/07 21:35:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/07 21:35:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/07 22:01:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "taken".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('taken')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('taken')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/taken')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/taken?grant_type=authorization_code&code=1083928674bc118b3b44a0588832447bbdf2fcba
---
2013/08/08 05:18:56 [error] [php] Undefined variable: supportedScopes (D:\www\OAuth2-for-Yii\protected\extensions\oauth2\OAuth.php:26)
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize?client_id=testclient&redirect_uri=http%3A%2F%2Flocalhost%2Fphp-openid-connect-client-master%2Fpublic%2Findex.php&response_type=code&scope=basic&state=4ac8a64444076b5a4300fcb659173217bb543f89141fbea59ca5e916d5445178
in D:\www\OAuth2-for-Yii\protected\extensions\oauth2\OAuth.php (26)
in D:\www\OAuth2-for-Yii\protected\controllers\Oauth2Controller.php (8)
in D:\www\OAuth2-for-Yii\index.php (13)
2013/08/08 05:19:11 [error] [php] Undefined variable: server (D:\www\OAuth2-for-Yii\protected\extensions\oauth2\OAuth.php:29)
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize?client_id=testclient&redirect_uri=http%3A%2F%2Flocalhost%2Fphp-openid-connect-client-master%2Fpublic%2Findex.php&response_type=code&scope=basic&state=4ac8a64444076b5a4300fcb659173217bb543f89141fbea59ca5e916d5445178
in D:\www\OAuth2-for-Yii\protected\extensions\oauth2\OAuth.php (29)
in D:\www\OAuth2-for-Yii\protected\controllers\Oauth2Controller.php (8)
in D:\www\OAuth2-for-Yii\index.php (13)
2013/08/08 08:22:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth
---
2013/08/08 08:22:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\www\framework\web\CController.php:483
Stack trace:
#0 D:\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2
---
2013/08/08 08:22:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\www\framework\web\CController.php:483
Stack trace:
#0 D:\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2
---
2013/08/08 08:22:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\www\framework\web\CController.php:483
Stack trace:
#0 D:\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/08 08:22:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index".' in D:\www\framework\web\CController.php:483
Stack trace:
#0 D:\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#3 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/08 08:23:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "register".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('register')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/register
---
2013/08/08 08:46:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth2/token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/token
---
2013/08/08 08:46:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth2/token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/token
---
2013/08/08 08:46:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth2/token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/token
---
2013/08/08 08:46:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth2/token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/token
---
2013/08/08 08:46:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth2/token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/token
---
2013/08/08 08:46:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth2/token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/token
---
2013/08/08 08:46:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth2/token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/token
---
2013/08/08 08:46:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth2/token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/token
---
2013/08/08 08:46:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth2/token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/token
---
2013/08/08 08:46:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oauth2/token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/token
---
2013/08/08 08:51:04 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 08:51:32 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 08:51:42 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 08:51:42 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 08:51:43 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 08:51:43 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 08:51:43 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 08:51:43 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 08:51:43 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 08:51:43 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 08:51:44 [error] [exception.CException] exception 'CException' with message 'Property "AuthorizeController.oauth" is not defined.' in D:\www\framework\base\CComponent.php:173
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__set('oauth', Object(OAuth))
#1 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(AuthorizeController), Object(CInlineAction))
#2 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/authorize
---
2013/08/08 09:01:05 [error] [exception.CException] exception 'CException' with message 'TokenController and its behaviors do not have a method or closure named "setOauth".' in D:\www\framework\base\CComponent.php:265
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__call('setOauth', Array)
#1 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): TokenController->setOauth(Object(OAuth))
#2 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(TokenController), Object(CInlineAction))
#3 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#4 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/token')
#5 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#6 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/token
HTTP_REFERER=http://localhost/OAuth2-for-Yii/index.php/gii/controller
---
2013/08/08 09:01:30 [error] [php] Undefined property: OAuth::$token (D:\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\TokenController.php:8)
Stack trace:
#0 D:\www\framework\web\CController.php(286): TokenController->runAction()
#1 D:\www\framework\web\CController.php(265): TokenController->runActionWithFilters()
#2 D:\www\framework\web\CWebApplication.php(282): TokenController->run()
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/token
in D:\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\TokenController.php (8)
in D:\www\OAuth2-for-Yii\index.php (13)
2013/08/08 09:18:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/
---
2013/08/09 03:02:56 [error] [exception.CException] exception 'CException' with message 'OauthController and its behaviors do not have a method or closure named "setOauth".' in D:\www\framework\base\CComponent.php:265
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): CComponent->__call('setOauth', Array)
#1 D:\www\OAuth2-for-Yii\protected\modules\oauth2\Oauth2Module.php(23): OauthController->setOauth(Object(OAuth))
#2 D:\www\framework\web\CController.php(263): Oauth2Module->beforeControllerAction(Object(OauthController), Object(CInlineAction))
#3 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#4 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/oauth')
#5 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#6 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/oauth
HTTP_REFERER=http://localhost/OAuth2-for-Yii/index.php/gii/controller
---
2013/08/09 03:16:15 [error] [php] Undefined property: OAuth::$oauth (D:\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php:8)
Stack trace:
#0 D:\www\framework\web\CController.php(286): AuthorizeController->runAction()
#1 D:\www\framework\web\CController.php(265): AuthorizeController->runActionWithFilters()
#2 D:\www\framework\web\CWebApplication.php(282): AuthorizeController->run()
#3 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#5 D:\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize
in D:\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php (8)
in D:\www\OAuth2-for-Yii\index.php (13)
2013/08/09 04:35:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 09:23:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 09:24:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 09:24:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 09:24:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 10:44:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 10:45:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 10:45:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 10:45:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 10:45:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 10:45:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/defau...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/default/login
---
2013/08/09 10:46:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token/default/l...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token/default/login
---
2013/08/09 10:52:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token/default/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token/default/l...')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token/default/login
---
2013/08/09 10:52:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token/
---
2013/08/09 10:52:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token/
---
2013/08/09 10:52:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token/
---
2013/08/09 10:52:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token/
---
2013/08/09 10:52:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token/
---
2013/08/09 10:52:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token/
---
2013/08/09 10:52:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token/
---
2013/08/09 10:52:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token
---
2013/08/09 10:52:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token
---
2013/08/09 10:52:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token
---
2013/08/09 10:52:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token
---
2013/08/09 10:52:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token
---
2013/08/09 10:52:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token
---
2013/08/09 10:52:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token
---
2013/08/09 10:52:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token
---
2013/08/09 10:52:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize
---
2013/08/09 10:53:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "token/login".' in D:\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('token/login')
#1 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/token/login
---
2013/08/09 21:16:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "authorize/login".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('authorize/login')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/authorize/login
HTTP_REFERER=http://localhost/client/
---
2013/08/09 21:26:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/oatuh2/authorize
---
2013/08/09 21:26:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:26:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:26:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:26:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:26:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:26:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:26:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:26:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:27:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:27:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:27:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:27:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:27:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:27:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oatuh2/authorize".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oatuh2/authoriz...')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oatuh2/authorize
---
2013/08/09 21:27:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize
---
2013/08/09 21:28:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "authorize".' in D:\srv\www\framework\web\CController.php:483
Stack trace:
#0 D:\srv\www\framework\web\CController.php(270): CController->missingAction('')
#1 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#2 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#3 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize
---
2013/08/09 21:45:37 [error] [php] include(OAuth.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php(33): spl_autoload_call()
#1 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php(10): AuthorizeController->getStorage()
#2 D:\srv\www\framework\web\actions\CInlineAction.php(49): AuthorizeController->actionIndex()
#3 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 D:\srv\www\framework\web\CController.php(286): AuthorizeController->runAction()
#5 D:\srv\www\framework\web\CController.php(265): AuthorizeController->runActionWithFilters()
#6 D:\srv\www\framework\web\CWebApplication.php(282): AuthorizeController->run()
#7 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php (33)
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php (10)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/09 21:46:25 [error] [php] include(OAuth.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php(33): spl_autoload_call()
#1 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php(10): AuthorizeController->getStorage()
#2 D:\srv\www\framework\web\actions\CInlineAction.php(49): AuthorizeController->actionIndex()
#3 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 D:\srv\www\framework\web\CController.php(286): AuthorizeController->runAction()
#5 D:\srv\www\framework\web\CController.php(265): AuthorizeController->runActionWithFilters()
#6 D:\srv\www\framework\web\CWebApplication.php(282): AuthorizeController->run()
#7 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php (33)
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php (10)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/09 21:46:26 [error] [php] include(OAuth.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php(33): spl_autoload_call()
#1 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php(10): AuthorizeController->getStorage()
#2 D:\srv\www\framework\web\actions\CInlineAction.php(49): AuthorizeController->actionIndex()
#3 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 D:\srv\www\framework\web\CController.php(286): AuthorizeController->runAction()
#5 D:\srv\www\framework\web\CController.php(265): AuthorizeController->runActionWithFilters()
#6 D:\srv\www\framework\web\CWebApplication.php(282): AuthorizeController->run()
#7 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php (33)
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php (10)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/09 21:46:26 [error] [php] include(OAuth.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php(33): spl_autoload_call()
#1 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php(10): AuthorizeController->getStorage()
#2 D:\srv\www\framework\web\actions\CInlineAction.php(49): AuthorizeController->actionIndex()
#3 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 D:\srv\www\framework\web\CController.php(286): AuthorizeController->runAction()
#5 D:\srv\www\framework\web\CController.php(265): AuthorizeController->runActionWithFilters()
#6 D:\srv\www\framework\web\CWebApplication.php(282): AuthorizeController->run()
#7 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php (33)
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php (10)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/09 21:46:26 [error] [php] include(OAuth.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php(33): spl_autoload_call()
#1 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php(10): AuthorizeController->getStorage()
#2 D:\srv\www\framework\web\actions\CInlineAction.php(49): AuthorizeController->actionIndex()
#3 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 D:\srv\www\framework\web\CController.php(286): AuthorizeController->runAction()
#5 D:\srv\www\framework\web\CController.php(265): AuthorizeController->runActionWithFilters()
#6 D:\srv\www\framework\web\CWebApplication.php(282): AuthorizeController->run()
#7 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php (33)
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php (10)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/09 21:46:46 [error] [php] include(OAuth.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php(33): spl_autoload_call()
#1 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php(10): AuthorizeController->getStorage()
#2 D:\srv\www\framework\web\actions\CInlineAction.php(49): AuthorizeController->actionIndex()
#3 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 D:\srv\www\framework\web\CController.php(286): AuthorizeController->runAction()
#5 D:\srv\www\framework\web\CController.php(265): AuthorizeController->runActionWithFilters()
#6 D:\srv\www\framework\web\CWebApplication.php(282): AuthorizeController->run()
#7 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php (33)
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php (10)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/09 21:46:46 [error] [php] include(OAuth.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php(33): spl_autoload_call()
#1 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php(10): AuthorizeController->getStorage()
#2 D:\srv\www\framework\web\actions\CInlineAction.php(49): AuthorizeController->actionIndex()
#3 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 D:\srv\www\framework\web\CController.php(286): AuthorizeController->runAction()
#5 D:\srv\www\framework\web\CController.php(265): AuthorizeController->runActionWithFilters()
#6 D:\srv\www\framework\web\CWebApplication.php(282): AuthorizeController->run()
#7 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php (33)
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php (10)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/09 21:46:47 [error] [php] include(OAuth.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php(33): spl_autoload_call()
#1 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php(10): AuthorizeController->getStorage()
#2 D:\srv\www\framework\web\actions\CInlineAction.php(49): AuthorizeController->actionIndex()
#3 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 D:\srv\www\framework\web\CController.php(286): AuthorizeController->runAction()
#5 D:\srv\www\framework\web\CController.php(265): AuthorizeController->runActionWithFilters()
#6 D:\srv\www\framework\web\CWebApplication.php(282): AuthorizeController->run()
#7 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php (33)
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php (10)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/09 21:46:47 [error] [php] include(OAuth.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php(33): spl_autoload_call()
#1 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php(10): AuthorizeController->getStorage()
#2 D:\srv\www\framework\web\actions\CInlineAction.php(49): AuthorizeController->actionIndex()
#3 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 D:\srv\www\framework\web\CController.php(286): AuthorizeController->runAction()
#5 D:\srv\www\framework\web\CController.php(265): AuthorizeController->runActionWithFilters()
#6 D:\srv\www\framework\web\CWebApplication.php(282): AuthorizeController->run()
#7 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php (33)
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php (10)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/09 23:11:23 [error] [exception.CException] exception 'CException' with message 'AuthorizeController cannot find the requested view "/default/login".' in D:\srv\www\framework\web\CController.php:878
Stack trace:
#0 D:\srv\www\framework\web\CController.php(782): CController->renderPartial('/default/login', NULL, true)
#1 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php(58): CController->render('/default/login')
#2 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php(41): OauthController->login()
#3 D:\srv\www\framework\web\actions\CInlineAction.php(49): OauthController->actionAuthorize()
#4 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#8 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#9 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize
---
2013/08/10 07:50:24 [error] [exception.CException] exception 'CException' with message 'AuthorizeController cannot find the requested view "/dafault/login".' in D:\www\framework\web\CController.php:878
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php(61): CController->renderPartial('/dafault/login')
#1 D:\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php(42): OauthController->login()
#2 D:\www\framework\web\actions\CInlineAction.php(49): OauthController->actionAuthorize()
#3 D:\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 D:\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#7 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#8 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize?client_id=testclient&response_type=code&state=5cf399ee1a6310f5&scope=openid
---
2013/08/10 07:52:01 [error] [exception.CException] exception 'CException' with message 'AuthorizeController cannot find the requested view "/authorize/login".' in D:\www\framework\web\CController.php:878
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php(61): CController->renderPartial('/authorize/logi...')
#1 D:\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php(42): OauthController->login()
#2 D:\www\framework\web\actions\CInlineAction.php(49): OauthController->actionAuthorize()
#3 D:\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 D:\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#7 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#8 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize?client_id=testclient&response_type=code&state=5cf399ee1a6310f5&scope=openid
---
2013/08/10 07:52:21 [error] [exception.CException] exception 'CException' with message 'AuthorizeController cannot find the requested view "/authorize/login".' in D:\www\framework\web\CController.php:878
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php(61): CController->renderPartial('/authorize/logi...')
#1 D:\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php(42): OauthController->login()
#2 D:\www\framework\web\actions\CInlineAction.php(49): OauthController->actionAuthorize()
#3 D:\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 D:\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#7 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#8 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize?client_id=testclient&response_type=code&state=5cf399ee1a6310f5&scope=openid
---
2013/08/10 07:55:53 [error] [exception.CException] exception 'CException' with message 'AuthorizeController cannot find the requested view "/aaa/aaa".' in D:\www\framework\web\CController.php:878
Stack trace:
#0 D:\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php(64): CController->renderPartial('/aaa/aaa')
#1 D:\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php(45): OauthController->login()
#2 D:\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php(10): OauthController->actionAuthorize()
#3 D:\www\framework\web\actions\CInlineAction.php(49): AuthorizeController->actionIndex()
#4 D:\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 D:\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 D:\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 D:\www\framework\web\CWebApplication.php(282): CController->run('')
#8 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#9 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 D:\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize?client_id=testclient&response_type=code&state=5cf399ee1a6310f5&scope=openid
---
2013/08/10 23:13:37 [error] [exception.CException] exception 'CException' with message 'DefaultController cannot find the requested view "index".' in D:\srv\www\framework\web\CController.php:878
Stack trace:
#0 D:\srv\www\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#1 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(9): CController->render('index')
#2 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#3 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#7 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#8 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2
---
2013/08/10 23:16:35 [error] [php] include_once(D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\config/dbconfig.php): failed to open stream: No such file or directory (D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php:9)
Stack trace:
#0 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 D:\srv\www\framework\web\CController.php(286): DefaultController->runAction()
#2 D:\srv\www\framework\web\CController.php(265): DefaultController->runActionWithFilters()
#3 D:\srv\www\framework\web\CWebApplication.php(282): DefaultController->run()
#4 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#6 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/oauth2/
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (9)
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (9)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 09:19:33 [error] [exception.CException] exception 'CException' with message 'Property "Oauth2Module.test" is not defined.' in D:\srv\www\framework\base\CComponent.php:130
Stack trace:
#0 D:\srv\www\framework\base\CModule.php(105): CComponent->__get('test')
#1 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(9): CModule->__get('test')
#2 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#3 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#7 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#8 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#9 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/OAuth2-for-Yii/oauth2/
---
2013/08/11 10:49:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "userq".' in D:\srv\www\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('userq')
#1 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/userq
HTTP_REFERER=http://localhost/OAuth2-for-Yii/index.php/gii/crud
---
2013/08/11 11:24:08 [error] [php] Missing argument 1 for OAuth::__construct(), called in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php on line 9 and defined (D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\extensions\oauth2\OAuth.php:19)
Stack trace:
#0 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 D:\srv\www\framework\web\CController.php(286): DefaultController->runAction()
#2 D:\srv\www\framework\web\CController.php(265): DefaultController->runActionWithFilters()
#3 D:\srv\www\framework\web\CWebApplication.php(282): DefaultController->run()
#4 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#6 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\extensions\oauth2\OAuth.php (19)
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (9)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 11:25:54 [error] [exception.CException] exception 'CException' with message 'Property "OAuthUser.module" is not defined.' in D:\srv\www\framework\base\CComponent.php:130
Stack trace:
#0 D:\srv\www\framework\db\ar\CActiveRecord.php(143): CComponent->__get('module')
#1 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\models\OAuthUser.php(25): CActiveRecord->__get('module')
#2 D:\srv\www\framework\db\ar\CActiveRecord.php(2308): OAuthUser->tableName()
#3 D:\srv\www\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(OAuthUser))
#4 D:\srv\www\framework\db\ar\CActiveRecord.php(402): CActiveRecord::model('OAuthUser')
#5 D:\srv\www\framework\db\ar\CActiveRecord.php(77): CActiveRecord->getMetaData()
#6 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(9): CActiveRecord->__construct()
#7 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#8 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#12 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#13 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#14 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/11 11:33:14 [error] [php] include(OAuthUser.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\controllers\SiteController.php(30): spl_autoload_call()
#1 D:\srv\www\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 D:\srv\www\framework\web\CController.php(286): SiteController->runAction()
#4 D:\srv\www\framework\web\CController.php(265): SiteController->runActionWithFilters()
#5 D:\srv\www\framework\web\CWebApplication.php(282): SiteController->run()
#6 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/
in D:\srv\www\OAuth2-for-Yii\protected\controllers\SiteController.php (30)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 11:42:46 [error] [exception.CException] exception 'CException' with message 'Property "CWebApplication.oauth" is not defined.' in D:\srv\www\framework\base\CComponent.php:130
Stack trace:
#0 D:\srv\www\framework\base\CModule.php(105): CComponent->__get('oauth')
#1 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\models\OAuthUser.php(25): CModule->__get('oauth')
#2 D:\srv\www\framework\db\ar\CActiveRecord.php(2308): OAuthUser->tableName()
#3 D:\srv\www\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(OAuthUser))
#4 D:\srv\www\framework\db\ar\CActiveRecord.php(402): CActiveRecord::model('OAuthUser')
#5 D:\srv\www\framework\db\ar\CActiveRecord.php(77): CActiveRecord->getMetaData()
#6 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(9): CActiveRecord->__construct()
#7 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#8 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#12 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#13 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#14 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/11 11:44:31 [error] [exception.CException] exception 'CException' with message 'Property "CWebApplication.oauth" is not defined.' in D:\srv\www\framework\base\CComponent.php:130
Stack trace:
#0 D:\srv\www\framework\base\CModule.php(105): CComponent->__get('oauth')
#1 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\models\OAuthUser.php(25): CModule->__get('oauth')
#2 D:\srv\www\framework\db\ar\CActiveRecord.php(2308): OAuthUser->tableName()
#3 D:\srv\www\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(OAuthUser))
#4 D:\srv\www\framework\db\ar\CActiveRecord.php(402): CActiveRecord::model('OAuthUser')
#5 D:\srv\www\framework\db\ar\CActiveRecord.php(77): CActiveRecord->getMetaData()
#6 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(9): CActiveRecord->__construct()
#7 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#8 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#12 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#13 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#14 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/11 11:52:10 [error] [exception.CException] exception 'CException' with message 'Property "CWebApplication.oauth" is not defined.' in D:\srv\www\framework\base\CComponent.php:130
Stack trace:
#0 D:\srv\www\framework\base\CModule.php(105): CComponent->__get('oauth')
#1 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\models\OAuthUser.php(25): CModule->__get('oauth')
#2 D:\srv\www\framework\db\ar\CActiveRecord.php(2308): OAuthUser->tableName()
#3 D:\srv\www\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(OAuthUser))
#4 D:\srv\www\framework\db\ar\CActiveRecord.php(402): CActiveRecord::model('OAuthUser')
#5 D:\srv\www\framework\db\ar\CActiveRecord.php(77): CActiveRecord->getMetaData()
#6 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(9): CActiveRecord->__construct()
#7 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#8 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#12 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#13 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#14 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/11 11:52:54 [error] [php] Missing argument 1 for OAuth::__construct(), called in D:\srv\www\framework\YiiBase.php on line 217 and defined (D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\extensions\oauth2\OAuth.php:19)
Stack trace:
#0 D:\srv\www\framework\base\CModule.php(103): Oauth2Module->getComponent()
#1 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\models\OAuthUser.php(25): Oauth2Module->__get()
#2 D:\srv\www\framework\db\ar\CActiveRecord.php(2308): OAuthUser->tableName()
#3 D:\srv\www\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct()
#4 D:\srv\www\framework\db\ar\CActiveRecord.php(402): model()
#5 D:\srv\www\framework\db\ar\CActiveRecord.php(77): OAuthUser->getMetaData()
#6 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(9): OAuthUser->__construct()
#7 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#8 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 D:\srv\www\framework\web\CController.php(286): DefaultController->runAction()
#10 D:\srv\www\framework\web\CController.php(265): DefaultController->runActionWithFilters()
#11 D:\srv\www\framework\web\CWebApplication.php(282): DefaultController->run()
#12 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#14 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\extensions\oauth2\OAuth.php (19)
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\models\OAuthUser.php (25)
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (9)
2013/08/11 12:02:00 [error] [exception.CException] exception 'CException' with message 'CDbAuthManager.connectionID "oauthdb" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\components\OAuthActiveRecord.php:30
Stack trace:
#0 D:\srv\www\framework\db\ar\CActiveRecord.php(2309): OAuthActiveRecord->getDbConnection()
#1 D:\srv\www\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(OAuthUser))
#2 D:\srv\www\framework\db\ar\CActiveRecord.php(402): CActiveRecord::model('OAuthUser')
#3 D:\srv\www\framework\db\ar\CActiveRecord.php(77): CActiveRecord->getMetaData()
#4 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(9): CActiveRecord->__construct()
#5 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#6 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#8 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#10 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#11 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#12 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/11 12:05:29 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'newzx.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (9)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 12:05:29 [error] [exception.CDbException] exception 'CDbException' with message 'The table "user" for active record class "OAuthUser" cannot be found in the database.' in D:\srv\www\framework\db\ar\CActiveRecord.php:2310
Stack trace:
#0 D:\srv\www\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(OAuthUser))
#1 D:\srv\www\framework\db\ar\CActiveRecord.php(402): CActiveRecord::model('OAuthUser')
#2 D:\srv\www\framework\db\ar\CActiveRecord.php(77): CActiveRecord->getMetaData()
#3 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(9): CActiveRecord->__construct()
#4 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#5 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#9 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#10 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/11 12:05:30 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'newzx.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (9)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 12:05:30 [error] [exception.CDbException] exception 'CDbException' with message 'The table "user" for active record class "OAuthUser" cannot be found in the database.' in D:\srv\www\framework\db\ar\CActiveRecord.php:2310
Stack trace:
#0 D:\srv\www\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(OAuthUser))
#1 D:\srv\www\framework\db\ar\CActiveRecord.php(402): CActiveRecord::model('OAuthUser')
#2 D:\srv\www\framework\db\ar\CActiveRecord.php(77): CActiveRecord->getMetaData()
#3 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(9): CActiveRecord->__construct()
#4 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#5 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#9 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#10 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/11 12:05:30 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'newzx.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (9)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 12:05:30 [error] [exception.CDbException] exception 'CDbException' with message 'The table "user" for active record class "OAuthUser" cannot be found in the database.' in D:\srv\www\framework\db\ar\CActiveRecord.php:2310
Stack trace:
#0 D:\srv\www\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(OAuthUser))
#1 D:\srv\www\framework\db\ar\CActiveRecord.php(402): CActiveRecord::model('OAuthUser')
#2 D:\srv\www\framework\db\ar\CActiveRecord.php(77): CActiveRecord->getMetaData()
#3 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(9): CActiveRecord->__construct()
#4 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#5 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#9 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#10 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/11 12:05:30 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'newzx.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (9)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 12:05:30 [error] [exception.CDbException] exception 'CDbException' with message 'The table "user" for active record class "OAuthUser" cannot be found in the database.' in D:\srv\www\framework\db\ar\CActiveRecord.php:2310
Stack trace:
#0 D:\srv\www\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(OAuthUser))
#1 D:\srv\www\framework\db\ar\CActiveRecord.php(402): CActiveRecord::model('OAuthUser')
#2 D:\srv\www\framework\db\ar\CActiveRecord.php(77): CActiveRecord->getMetaData()
#3 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(9): CActiveRecord->__construct()
#4 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#5 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#9 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#10 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/11 12:05:31 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'newzx.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (9)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 12:05:31 [error] [exception.CDbException] exception 'CDbException' with message 'The table "user" for active record class "OAuthUser" cannot be found in the database.' in D:\srv\www\framework\db\ar\CActiveRecord.php:2310
Stack trace:
#0 D:\srv\www\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(OAuthUser))
#1 D:\srv\www\framework\db\ar\CActiveRecord.php(402): CActiveRecord::model('OAuthUser')
#2 D:\srv\www\framework\db\ar\CActiveRecord.php(77): CActiveRecord->getMetaData()
#3 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(9): CActiveRecord->__construct()
#4 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#5 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#9 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#10 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/11 12:05:33 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'newzx.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (9)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 12:05:33 [error] [exception.CDbException] exception 'CDbException' with message 'The table "user" for active record class "OAuthUser" cannot be found in the database.' in D:\srv\www\framework\db\ar\CActiveRecord.php:2310
Stack trace:
#0 D:\srv\www\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(OAuthUser))
#1 D:\srv\www\framework\db\ar\CActiveRecord.php(402): CActiveRecord::model('OAuthUser')
#2 D:\srv\www\framework\db\ar\CActiveRecord.php(77): CActiveRecord->getMetaData()
#3 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(9): CActiveRecord->__construct()
#4 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#5 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#9 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#10 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/11 12:05:33 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'newzx.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (9)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 12:05:33 [error] [exception.CDbException] exception 'CDbException' with message 'The table "user" for active record class "OAuthUser" cannot be found in the database.' in D:\srv\www\framework\db\ar\CActiveRecord.php:2310
Stack trace:
#0 D:\srv\www\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(OAuthUser))
#1 D:\srv\www\framework\db\ar\CActiveRecord.php(402): CActiveRecord::model('OAuthUser')
#2 D:\srv\www\framework\db\ar\CActiveRecord.php(77): CActiveRecord->getMetaData()
#3 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(9): CActiveRecord->__construct()
#4 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#5 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#9 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#10 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/11 12:05:33 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'newzx.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (9)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 12:05:33 [error] [exception.CDbException] exception 'CDbException' with message 'The table "user" for active record class "OAuthUser" cannot be found in the database.' in D:\srv\www\framework\db\ar\CActiveRecord.php:2310
Stack trace:
#0 D:\srv\www\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(OAuthUser))
#1 D:\srv\www\framework\db\ar\CActiveRecord.php(402): CActiveRecord::model('OAuthUser')
#2 D:\srv\www\framework\db\ar\CActiveRecord.php(77): CActiveRecord->getMetaData()
#3 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(9): CActiveRecord->__construct()
#4 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#5 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#9 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#10 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/11 12:47:35 [error] [exception.CException] exception 'CException' with message 'CDbAuthManager.connectionID "oauthdb" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\components\OAuthActiveRecord.php:30
Stack trace:
#0 D:\srv\www\framework\db\ar\CActiveRecord.php(2309): OAuthActiveRecord->getDbConnection()
#1 D:\srv\www\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(OAuthUser))
#2 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\models\OAuthUser.php(17): CActiveRecord::model('OAuthUser')
#3 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(9): OAuthUser::model()
#4 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#5 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#9 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#10 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/11 12:55:36 [error] [exception.CException] exception 'CException' with message 'Property "OAuthUser.db" is not defined.' in D:\srv\www\framework\base\CComponent.php:130
Stack trace:
#0 D:\srv\www\framework\db\ar\CActiveRecord.php(143): CComponent->__get('db')
#1 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\components\OAuthActiveRecord.php(24): CActiveRecord->__get('db')
#2 D:\srv\www\framework\db\ar\CActiveRecord.php(2309): OAuthActiveRecord->getDbConnection()
#3 D:\srv\www\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(OAuthUser))
#4 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\models\OAuthUser.php(17): CActiveRecord::model('OAuthUser')
#5 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(10): OAuthUser::model()
#6 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#7 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#11 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#12 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#13 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/11 13:07:35 [error] [exception.CException] exception 'CException' with message 'CDbAuthManager.connectionID "oauthdb" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\components\OAuthActiveRecord.php:30
Stack trace:
#0 D:\srv\www\framework\db\ar\CActiveRecord.php(2309): OAuthActiveRecord->getDbConnection()
#1 D:\srv\www\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(OAuthUser))
#2 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\models\OAuthUser.php(17): CActiveRecord::model('OAuthUser')
#3 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(10): OAuthUser::model()
#4 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#5 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#9 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#10 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/11 13:22:03 [error] [exception.CException] exception 'CException' with message 'CDbAuthManager.connectionID "db" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\components\OAuthActiveRecord.php:30
Stack trace:
#0 D:\srv\www\framework\db\ar\CActiveRecord.php(2309): OAuthActiveRecord->getDbConnection()
#1 D:\srv\www\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(OAuthUser))
#2 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\models\OAuthUser.php(17): CActiveRecord::model('OAuthUser')
#3 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(10): OAuthUser::model()
#4 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#5 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#9 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2')
#10 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
---
2013/08/11 14:28:04 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(10): spl_autoload_call()
#1 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#2 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 D:\srv\www\framework\web\CController.php(286): DefaultController->runAction()
#4 D:\srv\www\framework\web\CController.php(265): DefaultController->runActionWithFilters()
#5 D:\srv\www\framework\web\CWebApplication.php(282): DefaultController->run()
#6 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (10)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 14:28:04 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(10): spl_autoload_call()
#1 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#2 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 D:\srv\www\framework\web\CController.php(286): DefaultController->runAction()
#4 D:\srv\www\framework\web\CController.php(265): DefaultController->runActionWithFilters()
#5 D:\srv\www\framework\web\CWebApplication.php(282): DefaultController->run()
#6 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (10)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 14:28:19 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(10): spl_autoload_call()
#1 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#2 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 D:\srv\www\framework\web\CController.php(286): DefaultController->runAction()
#4 D:\srv\www\framework\web\CController.php(265): DefaultController->runActionWithFilters()
#5 D:\srv\www\framework\web\CWebApplication.php(282): DefaultController->run()
#6 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (10)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 14:28:20 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(10): spl_autoload_call()
#1 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#2 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 D:\srv\www\framework\web\CController.php(286): DefaultController->runAction()
#4 D:\srv\www\framework\web\CController.php(265): DefaultController->runActionWithFilters()
#5 D:\srv\www\framework\web\CWebApplication.php(282): DefaultController->run()
#6 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (10)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 14:28:20 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(10): spl_autoload_call()
#1 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#2 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 D:\srv\www\framework\web\CController.php(286): DefaultController->runAction()
#4 D:\srv\www\framework\web\CController.php(265): DefaultController->runActionWithFilters()
#5 D:\srv\www\framework\web\CWebApplication.php(282): DefaultController->run()
#6 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (10)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 14:28:21 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(10): spl_autoload_call()
#1 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#2 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 D:\srv\www\framework\web\CController.php(286): DefaultController->runAction()
#4 D:\srv\www\framework\web\CController.php(265): DefaultController->runActionWithFilters()
#5 D:\srv\www\framework\web\CWebApplication.php(282): DefaultController->run()
#6 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (10)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 14:28:21 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(10): spl_autoload_call()
#1 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#2 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 D:\srv\www\framework\web\CController.php(286): DefaultController->runAction()
#4 D:\srv\www\framework\web\CController.php(265): DefaultController->runActionWithFilters()
#5 D:\srv\www\framework\web\CWebApplication.php(282): DefaultController->run()
#6 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (10)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 14:28:21 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(10): spl_autoload_call()
#1 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#2 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 D:\srv\www\framework\web\CController.php(286): DefaultController->runAction()
#4 D:\srv\www\framework\web\CController.php(265): DefaultController->runActionWithFilters()
#5 D:\srv\www\framework\web\CWebApplication.php(282): DefaultController->run()
#6 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (10)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 14:28:21 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(10): spl_autoload_call()
#1 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#2 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 D:\srv\www\framework\web\CController.php(286): DefaultController->runAction()
#4 D:\srv\www\framework\web\CController.php(265): DefaultController->runActionWithFilters()
#5 D:\srv\www\framework\web\CWebApplication.php(282): DefaultController->run()
#6 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (10)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 14:28:21 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(10): spl_autoload_call()
#1 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#2 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 D:\srv\www\framework\web\CController.php(286): DefaultController->runAction()
#4 D:\srv\www\framework\web\CController.php(265): DefaultController->runActionWithFilters()
#5 D:\srv\www\framework\web\CWebApplication.php(282): DefaultController->run()
#6 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (10)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 14:28:22 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php(10): spl_autoload_call()
#1 D:\srv\www\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#2 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 D:\srv\www\framework\web\CController.php(286): DefaultController->runAction()
#4 D:\srv\www\framework\web\CController.php(265): DefaultController->runActionWithFilters()
#5 D:\srv\www\framework\web\CWebApplication.php(282): DefaultController->run()
#6 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2
in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\DefaultController.php (10)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 19:09:27 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\controllers\SiteController.php(81): spl_autoload_call()
#1 D:\srv\www\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#2 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 D:\srv\www\framework\web\CController.php(286): SiteController->runAction()
#4 D:\srv\www\framework\web\CController.php(265): SiteController->runActionWithFilters()
#5 D:\srv\www\framework\web\CWebApplication.php(282): SiteController->run()
#6 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/site/login
in D:\srv\www\OAuth2-for-Yii\protected\controllers\SiteController.php (81)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 19:09:30 [error] [php] include(LoginForm.php): failed to open stream: No such file or directory (D:\srv\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\controllers\SiteController.php(81): spl_autoload_call()
#1 D:\srv\www\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#2 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 D:\srv\www\framework\web\CController.php(286): SiteController->runAction()
#4 D:\srv\www\framework\web\CController.php(265): SiteController->runActionWithFilters()
#5 D:\srv\www\framework\web\CWebApplication.php(282): SiteController->run()
#6 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#8 D:\srv\www\OAuth2-for-Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-for-Yii/index.php/site/login
in D:\srv\www\OAuth2-for-Yii\protected\controllers\SiteController.php (81)
in D:\srv\www\OAuth2-for-Yii\index.php (13)
2013/08/11 20:31:15 [error] [exception.InvalidArgumentException] exception 'InvalidArgumentException' with message 'Argument "is_authorized" must be a boolean.  This method must know if the user has granted access to the client.' in D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\extensions\oauth2\OAuth2\Controller\AuthorizeController.php:64
Stack trace:
#0 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\extensions\oauth2\OAuth2\Server.php(232): OAuth2\Controller\AuthorizeController->handleAuthorizeRequest(Object(OAuth2\Request), Object(OAuth2\Response), NULL, '1')
#1 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\extensions\oauth2\OAuth.php(80): OAuth2\Server->handleAuthorizeRequest(Object(OAuth2\Request), Object(OAuth2\Response), NULL, '1')
#2 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\OauthController.php(48): OAuth->authorize(NULL, '1')
#3 D:\srv\www\OAuth2-for-Yii\protected\modules\oauth2\controllers\AuthorizeController.php(10): OauthController->actionAuthorize()
#4 D:\srv\www\framework\web\actions\CInlineAction.php(49): AuthorizeController->actionIndex()
#5 D:\srv\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 D:\srv\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 D:\srv\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\srv\www\framework\web\CWebApplication.php(282): CController->run('')
#9 D:\srv\www\framework\web\CWebApplication.php(141): CWebApplication->runController('oauth2/authoriz...')
#10 D:\srv\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 D:\srv\www\OAuth2-for-Yii\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/OAuth2-for-Yii/index.php/oauth2/authorize?client_id=testclient&response_type=code&state=cca86d2afeef958e&scope=openid
---
2013/08/12 05:14:26 [error] [php] include(OAuth.php): failed to open stream: No such file or directory (D:\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\www\OAuth2-Server\protected\modules\oauth2\controllers\OauthController.php(39): spl_autoload_call()
#1 D:\www\OAuth2-Server\protected\modules\oauth2\controllers\OauthController.php(48): AuthorizeController->getStorage()
#2 D:\www\OAuth2-Server\protected\modules\oauth2\controllers\AuthorizeController.php(10): AuthorizeController->actionAuthorize()
#3 D:\www\framework\web\actions\CInlineAction.php(49): AuthorizeController->actionIndex()
#4 D:\www\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 D:\www\framework\web\CController.php(286): AuthorizeController->runAction()
#6 D:\www\framework\web\CController.php(265): AuthorizeController->runActionWithFilters()
#7 D:\www\framework\web\CWebApplication.php(282): AuthorizeController->run()
#8 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#10 D:\www\OAuth2-Server\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-Server/index.php/oauth2/authorize?client_id=testclient&response_type=code&state=dca32bae00f52b63&scope=openid
in D:\www\OAuth2-Server\protected\modules\oauth2\controllers\OauthController.php (39)
in D:\www\OAuth2-Server\protected\modules\oauth2\controllers\OauthController.php (48)
in D:\www\OAuth2-Server\protected\modules\oauth2\controllers\AuthorizeController.php (10)
2013/08/12 05:16:04 [error] [php] include(OauthController.php): failed to open stream: No such file or directory (D:\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\www\OAuth2-Server\protected\modules\oauth2\controllers\AuthorizeController.php(4): spl_autoload_call()
#1 D:\www\framework\web\CWebApplication.php(354): require()
#2 D:\www\framework\web\CWebApplication.php(338): CWebApplication->createController()
#3 D:\www\framework\web\CWebApplication.php(276): CWebApplication->createController()
#4 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#6 D:\www\OAuth2-Server\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-Server/index.php/oauth2/authorize?client_id=testclient&response_type=code&state=dca32bae00f52b63&scope=openid
in D:\www\OAuth2-Server\protected\modules\oauth2\controllers\AuthorizeController.php (4)
in D:\www\OAuth2-Server\index.php (13)
2013/08/12 05:16:04 [error] [php] include(OauthController.php): failed to open stream: No such file or directory (D:\www\framework\YiiBase.php:421)
Stack trace:
#0 D:\www\OAuth2-Server\protected\modules\oauth2\controllers\AuthorizeController.php(4): spl_autoload_call()
#1 D:\www\framework\web\CWebApplication.php(354): require()
#2 D:\www\framework\web\CWebApplication.php(338): CWebApplication->createController()
#3 D:\www\framework\web\CWebApplication.php(276): CWebApplication->createController()
#4 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#6 D:\www\OAuth2-Server\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-Server/index.php/oauth2/authorize?client_id=testclient&response_type=code&state=dca32bae00f52b63&scope=openid
in D:\www\OAuth2-Server\protected\modules\oauth2\controllers\AuthorizeController.php (4)
in D:\www\OAuth2-Server\index.php (13)
2013/08/12 05:16:45 [error] [php] include(D:\www\OAuth2-Server\protected\modules\oauth2\controller\OauthController.php): failed to open stream: No such file or directory (D:\www\framework\YiiBase.php:395)
Stack trace:
#0 D:\www\OAuth2-Server\protected\modules\oauth2\controllers\AuthorizeController.php(4): spl_autoload_call()
#1 D:\www\framework\web\CWebApplication.php(354): require()
#2 D:\www\framework\web\CWebApplication.php(338): CWebApplication->createController()
#3 D:\www\framework\web\CWebApplication.php(276): CWebApplication->createController()
#4 D:\www\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\www\framework\base\CApplication.php(169): CWebApplication->processRequest()
#6 D:\www\OAuth2-Server\index.php(13): CWebApplication->run()
REQUEST_URI=/OAuth2-Server/index.php/oauth2/authorize?client_id=testclient&response_type=code&state=dca32bae00f52b63&scope=openid
in D:\www\OAuth2-Server\protected\modules\oauth2\controllers\AuthorizeController.php (4)
in D:\www\OAuth2-Server\index.php (13)
